version: 0
metadata:
  name: Loop
  description: Loop CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    metadata:
      name: Loop Lint Tests
      description: Loop Lint Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "quay.io/mrrrgn/ubuntu-ci:0.0.1"
      command:
        - "/bin/bash"
        - "-lc"
        - "git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.base.repo.branch}} && make lint"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    metadata:
      name: Loop Unit Tests
      description: Loop Unit Tests (Karma/Mocha/Chai)
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "standard8/loop:latest"
      command:
        - "/bin/bash"
        - "-lc"
        - "git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.base.repo.branch}} && mozdownload --type=daily --branch=mozilla-central && tar xfj *.bz2 && FIREFOX_BIN=`pwd`/firefox/firefox make karma"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    metadata:
      name: Loop Functional Tests
      description: Loop Functional Tests (Marionette)
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "standard8/loop:latest"
      command:
        - "/bin/bash"
        - "-lc"
        - "git clone {{event.head.repo.url}} repo && cd repo && git checkout {{event.base.repo.branch}} && mozdownload --type=daily --branch=mozilla-central && tar xfj *.bz2 && TEST_BROWSER=`pwd`/firefox/firefox TEST_SERVER=dev make functional"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
