version: 0
metadata:
  name: Loop
  description: Loop CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "quay.io/mrrrgn/ubuntu-ci:0.0.2"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd loop && git checkout $GITHUB_HEAD_BRANCH && make install && make build && make lint"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
    metadata:
      name: Loop Lint Tests
      description: Loop Lint Tests
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
